repositories:
  - repo_slug: maflcko/DrahtBot
    backport_label: Backport
    repo_labels:
      Dummy:
        - '^dummy:'
    spam_detection: true
    ci_status: true
    external_sites: []
  - repo_slug: bitcoin-core/gui
    backport_label: null
    repo_labels:
    spam_detection: true
    ci_status: true
    external_sites: []
  - repo_slug: bitcoin-core/packaging
    backport_label: null
    repo_labels:
    spam_detection: true
    ci_status: false
    external_sites: []
  - repo_slug: bitcoin/bitcoin
    backport_label: Backport
    # labels taken from https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#creating-the-pull-request
    repo_labels:
      Build system:
        - '^guix:'
        - '^build:'
        - '^cmake:'
        - '^depends:'
      TX fees and policy:
        - '^fees:'
        - '^policy:'
      Utils/log/libs:
        - '^log:'
        - '^util:'
        - '^random:'
        - '^crypto:'
        - '^libs:'
        - '^compat:'
      UTXO Db and Indexes:
        - '^index:'
        - '^indexes:'
        - '^txdb:'
        - '^coins:'
        - '^db:'
      Block storage:
        - '^blockstorage:'
      PSBT:
        - '^psbt:'
      Validation:
        - '^validation:'
        - '^chain:'
        - '^kernel:'
      IPC:
        - '^interfaces:'
        - '^ipc:'
        - '^multiprocess:'
      Wallet:
        - '^wallet:'
      Descriptors:
        - '^descriptor:'
        - '^descriptors:'
        - '^miniscript:'
      Consensus:
        - '^consensus:'
        - '^versionbits:'
        - '^interpreter:'
        - '^script:'
        - '^sigcache:'
      GUI:
        - '^gui:'
        - '^qt:'
      Mempool:
        - '^mempool:'
        - '^txmempool:'
      Mining:
        - '^mining:'
        - '^miner:'
      P2P:
        - '^net:'
        - '^p2p:'
        - '^tor:'
        - '^addrman:'
        - '^protocol:'
        - '^net processing:'
      Private Broadcast:
        - '^private broadcast:'
      RPC/REST/ZMQ:
        - '^univalue:'
        - '^rpc:'
        - '^rest:'
        - '^zmq:'
        - '^http:'
      Scripts and tools:
        - '^contrib:'
        - '^tool:'
        - '^tools:'
        - '^cli:'
      Fuzzing:
        - '^fuzz:'
      Tests:
        - '^lint:'
        - '^qa:'
        - '^tests?:'
        - '^ci:'
        - '^bench:'
        - '^cirrus:'
      Docs:
        - '^docs?:'
      Backport:
        - '^backport:'
      Refactoring:
        - '^refactor(ing)?:'
        - '^move-?only:'
        - '^scripted-diff:'
    spam_detection: true
    ci_status: true
    external_sites:
      - 'Code coverage & benchmarks: https://corecheck.dev/{owner}/{repo}/pulls/{pull_num}'
      - 'Ralph review: https://git.fish.foo/{owner}/{repo}/pulls/{pull_num}#author-ralph'
